Add newlines to error echoes, correct ZLE hook invocations.

diff --git a/zsh/functions/downscale-jpegs b/zsh/functions/downscale-jpegs
--- a/zsh/functions/downscale-jpegs
+++ b/zsh/functions/downscale-jpegs
@@ -5,7 +5,7 @@
 # Creates, if needed, a "downscaled" subdir for the output, and converts to sRGB colorspace.
 # No-op if no files match.
 if ! (( ${+commands[vipsthumbnail]} )); then
-  echo "'vipsthumbnail' command not found, install the libvips package" >&2
+  echo -e "'vipsthumbnail' command not found, install the libvips package.\n" >&2
   return 1
 fi
 
diff --git a/zsh/functions/trustlog b/zsh/functions/trustlog
--- a/zsh/functions/trustlog
+++ b/zsh/functions/trustlog
@@ -3,14 +3,14 @@
 # Useful to debug repeated requests to allow access to directories.
 # Currently shows the last 24 hours, possibly worth parameterizing.
 if ! (( ${+commands[log]} )); then
-  echo "'log' command not found, this function is specific to macOS." >&2
+  echo -e "'log' command not found, this function is specific to macOS.\n" >&2
   return 1
 fi
 
 local timespan="24h"
 local query="$1"
 if [[ -z "$query" ]]; then
-  echo "No application name specified, showing full tccd debug log." >&2
+  echo -e "No application name specified, showing full tccd debug log.\n" >&2
   log show --predicate "process == \"tccd\"" --debug --last "${timespan}"
 else
   log show --predicate "process == \"tccd\" and eventMessage CONTAINS[c] \"${query}\"" --debug --last "${timespan}"
diff --git a/zsh/functions/zsh-compile b/zsh/functions/zsh-compile
--- a/zsh/functions/zsh-compile
+++ b/zsh/functions/zsh-compile
@@ -1,7 +1,7 @@
 #!/usr/bin/env zsh
 # Pre-compile zsh scripts for startup
 if [[ -z "${ZDOTDIR}" ]]; then
-  echo "Error: ZDOTDIR environment variable not configured. Aborting." >&2
+  echo -e "Error: ZDOTDIR environment variable not configured. Aborting.\n" >&2
   return 1
 fi
 
diff --git a/zsh/functions/zsh-update-completions b/zsh/functions/zsh-update-completions
--- a/zsh/functions/zsh-update-completions
+++ b/zsh/functions/zsh-update-completions
@@ -4,7 +4,7 @@
 # (At the cost of having two places to update when adding or removing such a utility)
 
 local compdir_local="${ZDOTDIR}/completions"
-[[ ! -d "${compdir_local}" ]] && { echo "Unable to find zsh completion cache directory at ${compdir_local}, aborting." >&2; return 1; }
+[[ ! -d "${compdir_local}" ]] && { echo -e "Unable to find zsh completion cache directory at ${compdir_local}, aborting.\n" >&2; return 1; }
 
 if (( "${+commands[uv]}" )); then
   "${commands[uv]}" generate-shell-completion zsh >| "${compdir_local}/_uv"
